// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChF-WI5dT6z1GItnCiJGM01UvEuDGTltI',
    appId: '1:526252732121:web:cd8a0badc0f84254d398c8',
    messagingSenderId: '526252732121',
    projectId: 'shinyspy-92103',
    authDomain: 'shinyspy-92103.firebaseapp.com',
    storageBucket: 'shinyspy-92103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpjoyKNj82GQyeJLuab9f5taXE7g5r9ck',
    appId: '1:526252732121:android:c2ba0d881210ff6dd398c8',
    messagingSenderId: '526252732121',
    projectId: 'shinyspy-92103',
    storageBucket: 'shinyspy-92103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAJTyZKBIoTLoERTSF2PblZb5DIakRMI',
    appId: '1:526252732121:ios:6371a2b48b88267fd398c8',
    messagingSenderId: '526252732121',
    projectId: 'shinyspy-92103',
    storageBucket: 'shinyspy-92103.appspot.com',
    iosBundleId: 'com.example.shinespy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAJTyZKBIoTLoERTSF2PblZb5DIakRMI',
    appId: '1:526252732121:ios:a1727e69abd83cb3d398c8',
    messagingSenderId: '526252732121',
    projectId: 'shinyspy-92103',
    storageBucket: 'shinyspy-92103.appspot.com',
    iosBundleId: 'com.example.shinespy.RunnerTests',
  );
}
